Fix fly.io deployment
[changelog skip]

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,9 +1,9 @@
 name: build
 on:
-  push: []
+  push: null
   schedule:
   - cron: 59 14 * * *
-  pull_request: []
+  pull_request: null
 
 jobs:
   build:
@@ -18,10 +18,19 @@ jobs:
         - "8.10"
         - "9.0"
         - "9.2"
+        exclude:
+        - os: macos-11
+          ghc-version: "8.10"
+        - os: macos-11
+          ghc-version: "9.0"
+        - os: windows-2022
+          ghc-version: "8.10"
+        - os: windows-2022
+          ghc-version: "9.0"
     env:
       STACK_YAML: stack-ghc-${{ matrix.ghc-version }}.yaml
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
     - uses: dahlia/actions/setup-yq@main
     - name: Cache Stack files (non-Windows)
       if: "!startsWith(matrix.os, 'windows-')"
@@ -135,7 +144,7 @@ jobs:
       matrix:
         os: [ubuntu-22.04, macos-11, windows-2022]
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
     - uses: denoland/setup-deno@v1
       with:
         deno-version: v1.x
@@ -212,66 +221,54 @@ jobs:
 
   image:
     name: Docker image
-    outputs:
-      image: ${{ steps.push-image.outputs.image }}
     runs-on: ubuntu-22.04
+    env:
+      DOCKERHUB_IMAGE_NAME: seonbi
+    outputs:
+      image-ghcr: ghcr.io/${{ github.repository }}/bin@${{ steps.push-image.outputs.digest }}
+      image-dockerhub: docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE_NAME }}@${{ steps.push-image.outputs.digest }}
     steps:
-    - uses: actions/checkout@v2
-    - id: push-image
+    - uses: actions/checkout@v3
+    - uses: docker/setup-buildx-action@v2
+    - if: github.event_name != 'pull_request'
+      uses: docker/login-action@v2
+      with:
+        registry: ghcr.io
+        username: ${{ github.repository_owner }}
+        password: ${{ github.token }}
+    - if: github.event_name != 'pull_request'
+      uses: docker/login-action@v2
+      with:
+        username: ${{ vars.DOCKERHUB_USERNAME }}
+        password: ${{ secrets.DOCKERHUB_TOKEN }}
+    - id: values
       run: |
-        image_name="dahlia/seonbi"
-        gh_image_name="docker.pkg.github.com/$GITHUB_REPOSITORY/bin"
-        declare -a build_opts=()
         if [[ "$GITHUB_EVENT_NAME" = "pull_request" ]]; then
-          sha="$(git log -n1 --format=%h)"
-          tag="git-$sha"
+          echo tag="git-$GITHUB_SHA" >> "$GITHUB_OUTPUT"
+        elif [[ "$GITHUB_REF" = "refs/heads/main" ]]; then
+          echo tag=latest >> "$GITHUB_OUTPUT"
         else
-          if [[ "$GITHUB_REF" = "refs/heads/main" ]]; then
-            tag=latest
-          elif [[ "$GITHUB_REF" = refs/tags/* ]]; then
-            tag="${GITHUB_REF:10}"
-            build_opts+=(--label "org.opencontainers.image.version=$tag")
-          else
-            tag="${GITHUB_REF:11}"
-          fi
+          echo tag="$GITHUB_REF_NAME" >> "$GITHUB_OUTPUT"
         fi
-        docker build \
-          --tag "$image_name:$tag" \
-          --tag "$gh_image_name:$tag" \
-          --label org.opencontainers.image.revision=`git log -1 --format=%H` \
-          --label \
-            org.opencontainers.image.url=https://github.com/$GITHUB_REPOSITORY \
-          --label org.opencontainers.image.description="$(cat README.md)" \
-          "${build_opts[@]}" \
-          .
-        if [[ "$GITHUB_EVENT_NAME" != "pull_request" ]]; then
-          docker login \
-            docker.pkg.github.com \
-            --username "${GITHUB_REPOSITORY#*/}" \
-            --password "${{ secrets.GH_TOKEN }}"
-          docker login \
-            --username "${image_name%/*}" \
-            --password "${{ secrets.DOCKERHUB_TOKEN }}"
-          docker push "$gh_image_name:$tag"
-          docker push "$image_name:$tag"
-          echo "::set-output name=image::$gh_image_name:$tag"
+        if [[ "$GITHUB_REF_TYPE" = tag ]]; then
+          echo labels=org.opencontainers.image.version="$GITHUB_REF_NAME" \
+            >> "$GITHUB_OUTPUT"
+        else
+          echo labels= >> "$GITHUB_OUTPUT"
         fi
-        docker save -o /tmp/image.tar "$image_name:$tag"
-        mkdir -p /tmp/images
-        pushd /tmp/images
-        tar xvf /tmp/image.tar
-        popd
-        mkdir -p /tmp/image-metadata
-        docker images "$image_name:$tag" | tail -n 1 | awk '{print $3}' \
-          > /tmp/image-metadata/image_id.txt
-    - uses: actions/upload-artifact@v3
+    - id: push-image
+      uses: docker/build-push-action@v4
       with:
-        name: image
-        path: /tmp/images
-    - uses: actions/upload-artifact@v3
-      with:
-        name: image-metadata
-        path: /tmp/image-metadata
+        context: .
+        push: ${{ github.event_name != 'pull_request' }}
+        labels: |
+          org.opencontainers.image.revision=${{ github.sha }}
+          org.opencontainers.image.url=${{ github.event.repository.html_url }}
+          ${{ steps.values.outputs.labels }}
+        tags: |
+          ghcr.io/${{ github.repository }}/bin:${{ steps.values.outputs.tag }}
+          ${{ vars.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE_NAME }}:${{ steps.values.outputs.tag }}
+        provenance: false  # https://community.fly.io/t/deploying-to-fly-via-github-action-failing/10171/33
 
   fly:
     name: Deploy seonbi-api to Fly.io
@@ -280,7 +277,7 @@ jobs:
     - image
     env:
       FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
-      IMAGE: ${{ needs.image.outputs.image }}
+      IMAGE: ${{ needs.image.outputs.image-ghcr }}
     runs-on: ubuntu-22.04
     steps:
     - uses: actions/checkout@v3
@@ -303,7 +300,7 @@ jobs:
     - image
     runs-on: ubuntu-22.04
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
     - uses: actions/download-artifact@v3
       with:
         name: binaries-macos-11-ghc-9.2
@@ -312,44 +309,34 @@ jobs:
       with:
         name: binaries-windows-2022-ghc-9.2
         path: /tmp/binaries-windows
-    - uses: actions/download-artifact@v3
-      with:
-        name: image
-        path: /tmp/images
-    - uses: actions/download-artifact@v3
-      with:
-        name: image-metadata
-        path: /tmp/image-metadata
     - run: |
-        workspace="${{ github.workspace }}"
+        set -e
         mkdir -p /tmp/dists
         # Linux
-        pushd /tmp/images
-        tar cvf ../image.tar .
-        popd
-        docker load -i /tmp/image.tar
+        docker pull "$IMAGE"
         mkdir -p /tmp/binaries-linux
-        image_id="$(cat /tmp/image-metadata/image_id.txt)"
-        docker run -i "$image_id" cat /usr/local/bin/seonbi \
+        docker run -i "$IMAGE" cat /usr/local/bin/seonbi \
           > /tmp/binaries-linux/seonbi
-        docker run -i "$image_id" cat /usr/local/bin/seonbi-api \
+        docker run -i "$IMAGE" cat /usr/local/bin/seonbi-api \
           > /tmp/binaries-linux/seonbi-api
         pushd /tmp/binaries-linux
         chmod +x *
-        cp "$workspace/"{LICENSE,README.md,CHANGES.md} ./
+        cp "$GITHUB_WORKSPACE/"{LICENSE,README.md,CHANGES.md} ./
         tar cvfj /tmp/dists/seonbi.linux-x86_64.tar.bz2 *
         popd
         # macOS
         pushd /tmp/binaries-macos
         chmod +x *
-        cp "$workspace/"{LICENSE,README.md,CHANGES.md} ./
+        cp "$GITHUB_WORKSPACE/"{LICENSE,README.md,CHANGES.md} ./
         tar cvfj /tmp/dists/seonbi.macos-x86_64.tar.bz2 *
         popd
         # Windows
         pushd /tmp/binaries-windows
-        cp "$workspace/"{LICENSE,README.md,CHANGES.md} ./
+        cp "$GITHUB_WORKSPACE/"{LICENSE,README.md,CHANGES.md} ./
         zip /tmp/dists/seonbi.win64.zip *
         popd
+      env:
+        IMAGE: ${{ needs.image.outputs.image-ghcr }}
     - uses: actions/upload-artifact@v3
       with:
         name: dists-untagged
@@ -362,7 +349,7 @@ jobs:
     - binaries
     runs-on: ubuntu-22.04
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
     - uses: actions/download-artifact@v3
       with:
         name: sdist-ubuntu-22.04-ghc-9.2
@@ -420,7 +407,7 @@ jobs:
       github.ref == 'refs/heads/main'
     runs-on: ubuntu-22.04
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
     - uses: actions/download-artifact@v3
       with:
         name: dists-untagged
